"""add max_depth to affiliate_ranks

Revision ID: 26c4a9892639
Revises: 04b948679dad
Create Date: 2026-02-18 11:26:02.913298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26c4a9892639'
down_revision: Union[str, None] = '04b948679dad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('affiliate_ranks', sa.Column('max_depth', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('affiliate_ranks', 'max_depth')
    # ### end Alembic commands ###
