"""Initial Schema

Revision ID: 04b948679dad
Revises: 
Create Date: 2026-02-15 18:58:14.692308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '04b948679dad'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_availability_ranges_id'), 'availability_ranges', ['id'], unique=False)
    op.drop_index(op.f('idx_call_bookings_time'), table_name='call_bookings')
    op.create_index(op.f('ix_call_bookings_id'), 'call_bookings', ['id'], unique=False)
    op.alter_column('call_services', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('call_services', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('call_services', 'duration_minutes',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('30'))
    op.alter_column('call_services', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('call_services', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('call_services', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_call_services_owner_id'), table_name='call_services')
    op.create_index(op.f('ix_call_services_id'), 'call_services', ['id'], unique=False)
    op.drop_constraint(op.f('call_services_owner_id_fkey'), 'call_services', type_='foreignkey')
    op.create_foreign_key(None, 'call_services', 'users', ['owner_id'], ['id'])
    op.drop_table_comment(
        'call_services',
        existing_comment='Configuración de oferta de llamadas privadas 1 a 1',
        schema=None
    )
    op.alter_column('call_slots', 'service_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('call_slots', 'start_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True)
    op.alter_column('call_slots', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_call_slots_booked_by_id'), table_name='call_slots')
    op.drop_index(op.f('idx_call_slots_is_booked'), table_name='call_slots')
    op.drop_index(op.f('idx_call_slots_service_id'), table_name='call_slots')
    op.drop_index(op.f('idx_call_slots_start_time'), table_name='call_slots')
    op.create_index(op.f('ix_call_slots_id'), 'call_slots', ['id'], unique=False)
    op.drop_constraint(op.f('call_slots_service_id_fkey'), 'call_slots', type_='foreignkey')
    op.drop_constraint(op.f('call_slots_booked_by_id_fkey'), 'call_slots', type_='foreignkey')
    op.create_foreign_key(None, 'call_slots', 'users', ['booked_by_id'], ['id'])
    op.create_foreign_key(None, 'call_slots', 'call_services', ['service_id'], ['id'])
    op.drop_table_comment(
        'call_slots',
        existing_comment='Slots de tiempo disponibles para llamadas',
        schema=None
    )
    op.alter_column('owner_legal_info', 'person_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Tipo de persona: natural o juridica',
               existing_nullable=False)
    op.drop_index(op.f('idx_owner_legal_info_contract_signed'), table_name='owner_legal_info')
    op.drop_index(op.f('idx_owner_legal_info_owner_id'), table_name='owner_legal_info')
    op.drop_index(op.f('idx_owner_legal_info_person_type'), table_name='owner_legal_info')
    op.create_index(op.f('ix_owner_legal_info_id'), 'owner_legal_info', ['id'], unique=False)
    op.drop_table_comment(
        'owner_legal_info',
        existing_comment='Información legal y tributaria de owners para contratos de mandato',
        schema=None
    )
    op.drop_index(op.f('payments_provider_tx_id_unique_idx'), table_name='payments', postgresql_where='(provider_tx_id IS NOT NULL)')
    op.alter_column('signature_codes', 'code',
               existing_type=sa.VARCHAR(length=6),
               comment=None,
               existing_comment='Código OTP de 6 dígitos enviado por Telegram',
               existing_nullable=False)
    op.drop_index(op.f('idx_signature_codes_code'), table_name='signature_codes')
    op.drop_index(op.f('idx_signature_codes_expires_at'), table_name='signature_codes')
    op.drop_index(op.f('idx_signature_codes_owner_id'), table_name='signature_codes')
    op.drop_index(op.f('idx_signature_codes_used'), table_name='signature_codes')
    op.create_index(op.f('ix_signature_codes_code'), 'signature_codes', ['code'], unique=False)
    op.create_index(op.f('ix_signature_codes_expires_at'), 'signature_codes', ['expires_at'], unique=False)
    op.create_index(op.f('ix_signature_codes_id'), 'signature_codes', ['id'], unique=False)
    op.create_index(op.f('ix_signature_codes_used'), 'signature_codes', ['used'], unique=False)
    op.drop_table_comment(
        'signature_codes',
        existing_comment='Códigos OTP temporales para firma de contratos vía Telegram',
        schema=None
    )
    op.alter_column('signed_contracts', 'blockchain_tx_hash',
               existing_type=sa.VARCHAR(length=66),
               comment=None,
               existing_comment='Hash de transacción en blockchain (Polygon)',
               existing_nullable=True)
    op.drop_index(op.f('idx_signed_contracts_owner_id'), table_name='signed_contracts')
    op.drop_index(op.f('idx_signed_contracts_pdf_hash'), table_name='signed_contracts')
    op.drop_index(op.f('idx_signed_contracts_signed_at'), table_name='signed_contracts')
    op.drop_index(op.f('idx_signed_contracts_tx_hash'), table_name='signed_contracts')
    op.create_index(op.f('ix_signed_contracts_blockchain_tx_hash'), 'signed_contracts', ['blockchain_tx_hash'], unique=False)
    op.create_index(op.f('ix_signed_contracts_id'), 'signed_contracts', ['id'], unique=False)
    op.create_index(op.f('ix_signed_contracts_pdf_hash'), 'signed_contracts', ['pdf_hash'], unique=False)
    op.create_index(op.f('ix_signed_contracts_signed_at'), 'signed_contracts', ['signed_at'], unique=False)
    op.drop_table_comment(
        'signed_contracts',
        existing_comment='Registro inmutable de contratos firmados con hash blockchain',
        schema=None
    )
    op.drop_index(op.f('idx_users_can_create_channels'), table_name='users')
    op.drop_index(op.f('idx_users_legal_status'), table_name='users')
    op.drop_index(op.f('users_email_unique_idx'), table_name='users', postgresql_where='(email IS NOT NULL)')
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.create_index(op.f('users_email_unique_idx'), 'users', ['email'], unique=True, postgresql_where='(email IS NOT NULL)')
    op.create_index(op.f('idx_users_legal_status'), 'users', ['legal_verification_status'], unique=False)
    op.create_index(op.f('idx_users_can_create_channels'), 'users', ['can_create_channels'], unique=False)
    op.create_table_comment(
        'signed_contracts',
        'Registro inmutable de contratos firmados con hash blockchain',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_signed_contracts_signed_at'), table_name='signed_contracts')
    op.drop_index(op.f('ix_signed_contracts_pdf_hash'), table_name='signed_contracts')
    op.drop_index(op.f('ix_signed_contracts_id'), table_name='signed_contracts')
    op.drop_index(op.f('ix_signed_contracts_blockchain_tx_hash'), table_name='signed_contracts')
    op.create_index(op.f('idx_signed_contracts_tx_hash'), 'signed_contracts', ['blockchain_tx_hash'], unique=False)
    op.create_index(op.f('idx_signed_contracts_signed_at'), 'signed_contracts', ['signed_at'], unique=False)
    op.create_index(op.f('idx_signed_contracts_pdf_hash'), 'signed_contracts', ['pdf_hash'], unique=False)
    op.create_index(op.f('idx_signed_contracts_owner_id'), 'signed_contracts', ['owner_id'], unique=False)
    op.alter_column('signed_contracts', 'blockchain_tx_hash',
               existing_type=sa.VARCHAR(length=66),
               comment='Hash de transacción en blockchain (Polygon)',
               existing_nullable=True)
    op.create_table_comment(
        'signature_codes',
        'Códigos OTP temporales para firma de contratos vía Telegram',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_signature_codes_used'), table_name='signature_codes')
    op.drop_index(op.f('ix_signature_codes_id'), table_name='signature_codes')
    op.drop_index(op.f('ix_signature_codes_expires_at'), table_name='signature_codes')
    op.drop_index(op.f('ix_signature_codes_code'), table_name='signature_codes')
    op.create_index(op.f('idx_signature_codes_used'), 'signature_codes', ['used'], unique=False)
    op.create_index(op.f('idx_signature_codes_owner_id'), 'signature_codes', ['owner_id'], unique=False)
    op.create_index(op.f('idx_signature_codes_expires_at'), 'signature_codes', ['expires_at'], unique=False)
    op.create_index(op.f('idx_signature_codes_code'), 'signature_codes', ['code'], unique=False)
    op.alter_column('signature_codes', 'code',
               existing_type=sa.VARCHAR(length=6),
               comment='Código OTP de 6 dígitos enviado por Telegram',
               existing_nullable=False)
    op.create_index(op.f('payments_provider_tx_id_unique_idx'), 'payments', ['provider_tx_id'], unique=True, postgresql_where='(provider_tx_id IS NOT NULL)')
    op.create_table_comment(
        'owner_legal_info',
        'Información legal y tributaria de owners para contratos de mandato',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_owner_legal_info_id'), table_name='owner_legal_info')
    op.create_index(op.f('idx_owner_legal_info_person_type'), 'owner_legal_info', ['person_type'], unique=False)
    op.create_index(op.f('idx_owner_legal_info_owner_id'), 'owner_legal_info', ['owner_id'], unique=False)
    op.create_index(op.f('idx_owner_legal_info_contract_signed'), 'owner_legal_info', ['contract_signed'], unique=False)
    op.alter_column('owner_legal_info', 'person_type',
               existing_type=sa.VARCHAR(length=20),
               comment='Tipo de persona: natural o juridica',
               existing_nullable=False)
    op.create_table_comment(
        'call_slots',
        'Slots de tiempo disponibles para llamadas',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'call_slots', type_='foreignkey')
    op.drop_constraint(None, 'call_slots', type_='foreignkey')
    op.create_foreign_key(op.f('call_slots_booked_by_id_fkey'), 'call_slots', 'users', ['booked_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('call_slots_service_id_fkey'), 'call_slots', 'call_services', ['service_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_call_slots_id'), table_name='call_slots')
    op.create_index(op.f('idx_call_slots_start_time'), 'call_slots', ['start_time'], unique=False)
    op.create_index(op.f('idx_call_slots_service_id'), 'call_slots', ['service_id'], unique=False)
    op.create_index(op.f('idx_call_slots_is_booked'), 'call_slots', ['is_booked'], unique=False)
    op.create_index(op.f('idx_call_slots_booked_by_id'), 'call_slots', ['booked_by_id'], unique=False)
    op.alter_column('call_slots', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('call_slots', 'start_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('call_slots', 'service_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table_comment(
        'call_services',
        'Configuración de oferta de llamadas privadas 1 a 1',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'call_services', type_='foreignkey')
    op.create_foreign_key(op.f('call_services_owner_id_fkey'), 'call_services', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_call_services_id'), table_name='call_services')
    op.create_index(op.f('idx_call_services_owner_id'), 'call_services', ['owner_id'], unique=False)
    op.alter_column('call_services', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('call_services', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('call_services', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('call_services', 'duration_minutes',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('30'))
    op.alter_column('call_services', 'price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('call_services', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_call_bookings_id'), table_name='call_bookings')
    op.create_index(op.f('idx_call_bookings_time'), 'call_bookings', ['service_id', 'start_time', 'end_time'], unique=False)
    op.drop_index(op.f('ix_availability_ranges_id'), table_name='availability_ranges')
    # ### end Alembic commands ###
